Repository Nosto/nosto-magento2, pull requests merged in 2018-12, with the labels that each got.

#355 Update composer update flag for Phan
  Jenkinsfile
Labels: bug

#348 Created command to remove connected nosto account
  Console/Command/NostoAccountConnectCommand.php
  Console/Command/NostoAccountRemoveCommand.php
  Helper/Cache.php
  Helper/Scope.php
  etc/di.xml
Labels: enhancement

#354 Create Pull Request Template
  .github/pull_request_template.md
Labels: enhancement, help wanted
