Repository Nosto/nosto-magento2, pull requests merged in 2018-06, with the labels that each got.

#277 Added batching to prevent the indexer from OOMing MySQL
  Model/Indexer/Product/Indexer.php
  composer.lock
Labels: bug

#279 Migrate to SDK Category & PageType
  Block/Category.php
  Block/PageType.php
  composer.json
Labels: enhancement

#280 Removes ObjectManager
  Model/Cart/Builder.php
  Model/Cart/Item/Builder.php
  Model/Cart/Item/Grouped.php
  Model/Order/Builder.php
  Model/Order/Item/Builder.php
  Model/Order/Item/Grouped.php
Labels: Refactoring

#281 Add Multiple Products To Cart
  view/frontend/web/js/recobuy.js
Labels: enhancement

#284 Fix Issue With Configurable Products
  Helper/Price.php
Labels: bug

#285 Hotfix -2.10.4
  CHANGELOG.md
  Helper/Price.php
  composer.json
  etc/module.xml
Labels: bug

#287 Hotfix/Product Availability Missing Catalog Visibility Check
  CHANGELOG.md
  Model/Product/Builder.php
  Model/Product/Sku/Builder.php
  composer.json
  etc/module.xml
Labels: bug
