Repository Nosto/nosto-magento2, pull requests merged in 2019-10, with the labels that each got.

#562 Feature - Define minimal Magento 2 Version as 2.2.6 on composer.json
  composer.json
  composer.lock
Labels: enhancement

#563 Cleanup cl tables automatically
  Model/Indexer/AbstractIndexer.php
  Model/Indexer/Data.php
  Model/Indexer/Invalidate.php
Labels: enhancement

#564 Prevent full reindex on setup upgrade for both indexers
  Model/Indexer/AbstractIndexer.php
  Model/Indexer/Data.php
  Model/Indexer/Invalidate.php
  etc/di.xml
Labels: enhancement

#567 Bug - fix case of bundle products without options
  Model/Service/Index.php
Labels: bug

#569 WIP - fixes and refactoring
  Block/Product.php
  Cron/Invalidate.php
  Model/Indexer/AbstractIndexer.php
  Model/Indexer/Data.php
  Model/Indexer/Invalidate.php
  Model/Product/Collection.php
  Model/Product/Index/Index.php
  Model/Service/Indexer/IndexService.php
  Model/Service/Indexer/IndexerStatusService.php
  Model/Service/Indexer/IndexerStatusServiceInterface.php
  Model/Service/Product/CachingProductService.php
  Model/Service/Product/DefaultProductService.php
  Model/Service/Product/ProductServiceInterface.php
  Model/Service/Product/SanitizingProductService.php
  Model/Service/Stock/Provider/CachingStockProvider.php
  Model/Service/Sync/SyncService.php
  etc/di.xml
Labels: Refactoring

#572 Handle indexed products without data and not marked as dirty
  Api/Data/ProductIndexInterface.php
  Model/Product/Index/Index.php
  Model/Service/Sync/SyncService.php
Labels: bug

#575 WIP - Rename Index entity to Cache
  Api/Data/ProductCacheInterface.php
  Api/Data/ProductCacheSearchResultsInterface.php
  Api/Data/ProductIndexSearchResultsInterface.php
  Api/Data/ProductQueueSearchResultsInterface.php
  Api/ProductCacheRepositoryInterface.php
  Block/Adminhtml/Form/Field/Indexers.php
  Cron/Invalidate.php
  Model/Indexer/Dimensions/Invalidate/ModeSwitcherConfiguration.php
  Model/Indexer/Dimensions/StoreDimensionProvider.php
  Model/Product/Cache.php
  Model/Product/Cache/CacheBuilder.php
  Model/Product/Cache/CacheRepository.php
  Model/Product/Cache/CacheSearchResults.php
  Model/Product/Index/Builder.php
  Model/ResourceModel/Product/Cache.php
  Model/ResourceModel/Product/Cache/CacheCollection.php
  Model/Service/Indexer/IndexService.php
  Model/Service/Product/CachingProductService.php
  Model/Service/Sync/AsyncBulkConsumer.php
  Model/Service/Sync/AsyncBulkPublisher.php
  Model/Service/Sync/BulkSyncInterface.php
  Model/Service/Sync/SyncService.php
  Observer/Adminhtml/Config.php
  Plugin/ProductData.php
  Setup/Core.php
  Setup/InstallSchema.php
  Setup/UpgradeSchema.php
  etc/di.xml
Labels: enhancement

#576 Rename cache and data service refactoring
  Model/Indexer/AbstractIndexer.php
  Model/Indexer/Data.php
  Model/Indexer/Invalidate.php
  Model/ResourceModel/Product/Cache.php
  Model/Service/Cache/CacheService.php
  Model/Service/Product/CachingProductService.php
  etc/di.xml
  etc/mview.xml
Labels: enhancement

#579 Consolidate collection usage & introduce collection builder
  Block/Product.php
  Controller/Export/Product.php
  Model/Indexer/Invalidate.php
  Model/Product/CollectionBuilder.php
  Model/ResourceModel/Magento/Product/CollectionBuilder.php
  Model/Service/Product/ProductServiceInterface.php
  Model/Service/Sync/Upsert/SyncService.php
  etc/di.xml
Labels: bug

#581 Rename and move product services
  Model/Indexer/Invalidate.php
  Model/Service/Cache/CacheService.php
  Model/Service/Product/CachingProductService.php
  Model/Service/Product/DefaultProductComparator.php
  Model/Service/Product/DefaultProductSerializer.php
  Model/Service/Product/ProductComparatorInterface.php
  Model/Service/Product/ProductSerializerInterface.php
  Model/Service/Sync/Upsert/SyncService.php
  Util/Serializer/SerializerInterface.php
  etc/di.xml
Labels: enhancement

#583 Ensure the emulation is cleared
  CHANGELOG.md
  Model/Indexer/AbstractIndexer.php
  Model/Indexer/Data.php
  Setup/UpgradeSchema.php
  composer.json
  etc/module.xml
Labels: enhancement

#582 Feature- Add mem check to indexers
  Model/Indexer/Data.php
  Model/Indexer/Invalidate.php
  Model/Service/Cache/CacheService.php
Labels: enhancement

#585 Add null check for empty product data
  Model/Service/Product/SanitizingProductService.php
Labels: bug

#586 Add null check after building Nosto product
  Model/Product/Builder.php
  Model/Service/Cache/CacheService.php
Labels: enhancement

#587 Handle product building errors and make them visible
  Block/Product.php
  Model/Product/Builder.php
  Model/Product/CollectionBuilder.php
  Model/Service/Cache/CacheService.php
  Model/Service/Product/DefaultProductService.php
  composer.json
  composer.lock
  etc/di.xml
Labels: enhancement

#588 Refactor - add indexer suffixes, log exceptions & move collection building to repo
  Cron/InvalidateCron.php
  Cron/RatesCron.php
  Helper/Account.php
  Helper/Variation.php
  Model/Indexer/DataIndexer.php
  Model/Indexer/InvalidateIndexer.php
  Model/Person/Tagging/Builder.php
  Model/Product/Cache/CacheRepository.php
  Model/Service/Cache/CacheService.php
  Observer/Order/Save.php
  Observer/Product/Base.php
  Plugin/ProductData.php
  Plugin/ProductInvalidate.php
  etc/crontab.xml
  etc/di.xml
  etc/indexer.xml
  etc/mview.xml
Labels: enhancement

#590 Fix the rating helper to check the return type for getRatingSummary
  CHANGELOG.md
  Dockerfile
  Helper/Ratings.php
  Jenkinsfile
  composer.json
  etc/module.xml
Labels: bug
