Repository Nosto/nosto-magento2, pull requests merged in 2019-06, with the labels that each got.

#477 Fix possible method call on null when order sending to Nosto fails
  CHANGELOG.md
  Observer/Order/Save.php
  composer.json
  etc/module.xml
Labels: bug

#472 Use customer_ref in case of missing customer id
  Helper/Data.php
  Observer/Order/Save.php
  etc/adminhtml/system.xml
  etc/config.xml
Labels: enhancement

#480 Remove product cache flushing after upsert
  CHANGELOG.md
  Model/Product/Service.php
  composer.json
  etc/module.xml
Labels: bug

#479 Feature - enable preview mode in graphql
  Model/Service/Recommendation/Category.php
Labels: enhancement

#481 Add Inventory Level to SKU
  CHANGELOG.md
  Model/Product/Sku/Builder.php
  composer.json
  composer.lock
Labels: enhancement

#483 Add Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement

#464 Feature Add first integration tests
  Dockerfile
  Test/Integration/Block/EmbedTest.php
  Test/Integration/Block/ProductTaggingTest.php
  Test/Integration/FixturesTrait.php
  Test/Integration/TestCase.php
  Test/_util/BuilderInterface.php
  Test/_util/ProductBuilder.php
  composer.json
  dev/tests/docker-compose.yml
  dev/tests/integration/etc/install-config-mysql.php
  dev/tests/integration/phpunit.xml
Labels: Test, enhancement

#486 Hotfix - 3.8.1
  CHANGELOG.md
  Setup/UpgradeData.php
  Setup/UpgradeSchema.php
  composer.json
  composer.lock
  etc/module.xml
Labels: bug

#491 Hotfix 3.8.2 - Fix redirect uri for multistore setup
  CHANGELOG.md
  Model/Meta/Oauth/Builder.php
  composer.json
  etc/module.xml
Labels: bug

#492 Order integration tests
  Test/Integration/Block/OrderTaggingTest.php
  Test/Integration/TestCase.php
  Test/_util/OrderBuilder.php
Labels: Test
