Repository Nosto/nosto-magento2, pull requests merged in 2019-09, with the labels that each got.

#528 Remove proxies from constructors and use di.xml to define them
  CHANGELOG.md
  Helper/Customer.php
  Model/Indexer/Product/Indexer.php
  Model/Product/Repository.php
  Model/Product/Service.php
  composer.json
  etc/di.xml
  etc/module.xml
Labels: Refactoring, bug

#526 Refactor - add filtering logic to collections
  .gitignore
  Model/Indexer/Data.php
  Model/Indexer/Invalidate.php
  Model/Product/Index/IndexRepository.php
  Model/ResourceModel/Magento/Product/Collection.php
  Model/ResourceModel/Product/Index/Collection.php
  Model/Service/Index.php
Labels: enhancement

#533 Remove array constructor comparison from recobuy addMultipleProductsT…
  CHANGELOG.md
  composer.json
  etc/module.xml
  view/frontend/web/js/recobuy.js
Labels: bug

#532 Refactoring - clean codebase from unused classes
  Cron/Prices.php
  Model/Product/Queue.php
  Model/Product/QueueRepository.php
  Model/Product/QueueSearchResults.php
  Model/Product/Repository.php
  Model/Product/Service.php
  Model/ResourceModel/Product/Queue.php
  Model/ResourceModel/Product/Queue/Collection.php
  Observer/Product/Base.php
  Setup/Core.php
  Setup/InstallSchema.php
  Setup/UpgradeSchema.php
  etc/crontab.xml
  etc/events.xml
Labels: Refactoring

#537 Feature/prevent full reindex on setup upgrade
  Console/Command/NostoRebuildIndexCommand.php
  Model/Indexer/Invalidate.php
  Model/Service/Index.php
  Model/Service/Sync.php
  Util/Benchmark.php
  Util/Indexer.php
  etc/di.xml
Labels: enhancement

#535 Feature/cronjob invalidate data
  Cron/Invalidate.php
  Model/ResourceModel/Product/Index/Collection.php
  etc/cron_groups.xml
  etc/crontab.xml
Labels: enhancement

#545 Feature/introduce injectable serializer
  Api/Data/ProductIndexInterface.php
  Model/Product/Index/Index.php
  Model/Service/CachingProductService.php
  Model/Service/Index.php
  Model/Service/Sync.php
  Util/Serializer/DefaultSerializer.php
  Util/Serializer/ProductSerializer.php
  Util/Serializer/SerializerInterface.php
  etc/di.xml
Labels: enhancement

#551 Hotfix - Product availability on single store mode
  CHANGELOG.md
  Model/Product/Builder.php
  Model/Product/BuilderTrait.php
  Model/Product/Sku/Builder.php
  composer.json
  etc/module.xml
Labels: bug

#549 Speed up inventory lookups
  Model/Product/Builder.php
  Model/Product/BuilderTrait.php
  Model/Product/Sku/Builder.php
  Model/Service/Stock/Provider/CachingStockProvider.php
  Model/Service/Stock/Provider/DefaultStockProvider.php
  Model/Service/Stock/Provider/StockProviderInterface.php
  Model/Service/Stock/Provider/StockRegistryProvider.php
  Model/Service/Stock/StockService.php
  etc/di.xml
Labels: Refactoring, enhancement

#552 Refactor logic for checking where the full reindex is called
  Model/Indexer/Invalidate.php
  Util/Indexer.php
  etc/di.xml
  phan.php
Labels: Refactoring

#554 Implement injectable product comparator
  Model/Service/Comparator/DefaultProductComparator.php
  Model/Service/Comparator/ProductComparatorInterface.php
  Model/Service/Index.php
  etc/di.xml
Labels: enhancement

#555 Bugfixes - Incorrect product URL and product data not generated from CachingProductService
  Model/Indexer/AbstractIndexer.php
  Model/Indexer/Data.php
  Model/Indexer/Invalidate.php
  Model/Service/CachingProductService.php
Labels: bug
