Repository Nosto/nosto-magento2, pull requests merged in 2019-03, with the labels that each got.

#386 Add possibility to define Nosto account & active domain
  Helper/Url.php
  Model/Product/Service.php
  Observer/Order/Save.php
  composer.json
  composer.lock
Labels: enhancement

#390 Feature - Make tokens visible in store
  Block/Adminhtml/Form/Field/Tokens.php
  etc/adminhtml/system.xml
  view/adminhtml/templates/tokens.phtml
Labels: enhancement

#395 Save installation domain when creating or connecting Nosto account
  Helper/Account.php
  Model/System/Message/Notification/InvalidAccount.php
  etc/adminhtml/di.xml
Labels: enhancement

#400 Refactor: Pass value of method to var
  view/adminhtml/templates/tokens.phtml
Labels: Refactoring

#401 Disable price variation when multicurrency is enabled
  Model/Config/Backend/MultiCurrency.php
  etc/adminhtml/system.xml
Labels: bug

#399 Skip non-scalar values in Product Builder Trait and Tag selector
  Model/Config/Source/Selector.php
  Model/Product/BuilderTrait.php
  composer.json
  composer.lock
Labels: bug, enhancement

#406 Hotfix 3.2.1 - Fix empty minPrice array problem when bundle product has no options
  CHANGELOG.md
  Helper/Price.php
  composer.json
  etc/module.xml
Labels: bug

#408 Hotfix 3.2.1 - Fix empty minPrice array problem when bundle product has no options
  CHANGELOG.md
  Helper/Price.php
  composer.json
  etc/module.xml
Labels: bug

#411 Hotfix - 3.2.2 Insert missing storefront domain in db when upgrading module
  CHANGELOG.md
  Setup/UpgradeData.php
  composer.json
  etc/module.xml
Labels: bug
