Repository Nosto/nosto-magento2, pull requests merged in 2019-05, with the labels that each got.

#436 Hotfix/3.4.1
  CHANGELOG.md
  Model/Product/Variation/Builder.php
  composer.json
  etc/module.xml
Labels: bug

#441 Define dependencies as proxies
  Console/Command/NostoAccountConnectCommand.php
  Console/Command/NostoAccountRemoveCommand.php
  etc/di.xml
Labels: enhancement

#442 Clear dependency injection
  Plugin/Block/Toolbar.php
  Plugin/Catalog/Model/Config.php
  Plugin/Catalog/Model/Sortby.php
Labels: Refactoring

#439 Add Nosto Customer Reference
  CHANGELOG.md
  CustomerData/CustomerTagging.php
  Helper/Data.php
  Setup/UpgradeData.php
  composer.json
  etc/module.xml
Labels: enhancement

#447 Feature/enrich customer data tagging
  CustomerData/CustomerTagging.php
  Model/Order/Buyer/Builder.php
  Model/Person/Builder.php
  Model/Person/Tagging/Builder.php
  view/frontend/templates/customer.phtml
Labels: enhancement

#451 Category Personalization - Ignore product ids if they are not numeric
  Model/Service/Recommendation/Category.php
Labels: bug, enhancement

#454 Bump SDK to 3.14.1
  composer.json
  composer.lock
Labels: enhancement

#453 Bug/add customer reference on install
  Helper/Data.php
  Setup/CoreData.php
  Setup/InstallData.php
  Setup/UpgradeData.php
Labels: bug

#457 Release 3.7.0
  CHANGELOG.md
  Helper/Data.php
  Model/Service/Recommendation/Category.php
  Setup/CoreData.php
  Setup/InstallData.php
  Setup/UpgradeData.php
  composer.json
  composer.lock
  etc/module.xml
Labels: enhancement

#459 Hotfix/fix marketing permission
  CHANGELOG.md
  Model/Email/Repository.php
  composer.json
  etc/module.xml
Labels: bug

#461 Hotfix/3.7.2 - Fix wrong store issue when connecting account
  CHANGELOG.md
  Controller/Oauth/Index.php
  composer.json
  etc/module.xml
  view/frontend/templates/jsstub.phtml
Labels: bug

#466 Feature - Generate customer_reference automatically
  Observer/Customer/Save.php
  etc/events.xml
Labels: enhancement

#468 Add nullcheck for products key in add to cart override
  CHANGELOG.md
  Controller/Checkout/Cart/Add.php
  composer.json
  etc/module.xml
Labels: bug

#470 Bugfix - customer group id from session
  CHANGELOG.md
  Helper/Customer.php
Labels: bug
