Repository Nosto/nosto-magento2, pull requests merged in 2020-05, with the labels that each got.

#674 Handle empty cache entries and failures in product building
  CHANGELOG.md
  Model/Service/Product/CachingProductService.php
  composer.json
  etc/module.xml
Labels: bug

#675 Add google category tagging feature flag and to product builder
  .github/workflows/phan.yml
  Helper/Data.php
  Model/Config/Source/GoogleCategory.php
  Model/Product/Builder.php
  etc/adminhtml/system.xml
Labels: enhancement

#671 Feature/use magentos built in caching for product data
  .github/workflows/phan.yml
  Api/Data/ProductCacheInterface.php
  Api/Data/ProductCacheSearchResultsInterface.php
  Helper/Data.php
  Model/Cache/Type/ProductData.php
  Model/Cache/Type/ProductDataInterface.php
  Model/Product/Cache.php
  Model/Product/Cache/CacheBuilder.php
  Model/Product/Cache/CacheRepository.php
  Model/Product/Queue/QueueRepository.php
  Model/ResourceModel/Product/Cache.php
  Model/ResourceModel/Product/Cache/CacheCollection.php
  Model/Service/Cache/CacheService.php
  Model/Service/Product/CachingProductService.php
  Model/Service/Sync/Delete/DeleteService.php
  Model/Service/Sync/Upsert/SyncService.php
  Setup/Core.php
  Setup/InstallSchema.php
  Setup/UpgradeData.php
  Setup/UpgradeSchema.php
  composer.lock
  etc/adminhtml/system.xml
  etc/cache.xml
  etc/di.xml
  phan.php
Labels: enhancement

#627 Update SDK Namespaces
  Block/Adminhtml/Form/Field/Tokens.php
  Block/Category.php
  Block/Email/ImageUrl.php
  Block/Order.php
  Block/PageType.php
  Block/Product.php
  Block/Search.php
  Block/Variation.php
  Console/Command/NostoAccountConnectCommand.php
  Controller/Export/Base.php
  Controller/Export/Order.php
  Controller/Export/Product.php
  CustomerData/CartTagging.php
  Helper/Account.php
  Model/Cart/Builder.php
  Model/Cart/Item/Builder.php
  Model/Category/Builder.php
  Model/Meta/Account/Billing/Builder.php
  Model/Meta/Account/Builder.php
  Model/Meta/Account/Iframe/Builder.php
  Model/Meta/Account/Owner/Builder.php
  Model/Meta/Account/Settings/Builder.php
  Model/Meta/Account/Settings/Currencies/Builder.php
  Model/Meta/Account/Sso/Builder.php
  Model/Meta/Oauth/Builder.php
  Model/Order/Builder.php
  Model/Order/Buyer/Builder.php
  Model/Order/Collection.php
  Model/Order/Item/Builder.php
  Model/Order/Status/Builder.php
  Model/Person/Builder.php
  Model/Person/Tagging/Builder.php
  Model/Product/Builder.php
  Model/Product/CollectionBuilder.php
  Model/Product/Sku/Builder.php
  Model/Product/Sku/Collection.php
  Model/Product/Variation/Builder.php
  Model/Product/Variation/Collection.php
  Model/Rates/Builder.php
  Model/Service/Product/DefaultProductSerializer.php
  Model/Service/Product/DefaultProductService.php
  Model/Service/Product/ProductSerializerInterface.php
  Model/Service/Product/ProductServiceInterface.php
  Model/Service/Product/SanitizingProductService.php
  Model/Service/Sync/Delete/DeleteService.php
  Model/User/Builder.php
  Observer/Cart/Add.php
  Observer/Order/Save.php
  Setup/UpgradeData.php
  composer.json
  composer.lock
Labels: Refactoring, enhancement

#679 Add null guard after product cache rebuild
  CHANGELOG.md
  Model/Service/Product/CachingProductService.php
  composer.json
  etc/module.xml
Labels: bug

#680 Hotfix/4.0.9
  CHANGELOG.md
  Model/Product/Repository.php
  Model/ResourceModel/Magento/Product/Collection.php
  Model/ResourceModel/Sku.php
  Model/Service/Stock/Provider/CachingStockProvider.php
  Model/Service/Stock/Provider/DefaultStockProvider.php
  Model/Service/Stock/Provider/StockProviderInterface.php
  composer.json
  etc/module.xml
Labels: bug
